### CREATE SONG
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Where are U now v2",
    "artists": ["Justin Bieber", "Diplo"],
    "album": "Where are U now v2",
    "releasedDate": "2024-04-30",
    "duration": "02:34"
}

### FETCH ALL SONGS
GET http://localhost:3000/songs

### FETCH SINGLE SONG
GET http://localhost:3000/songs/123

### UPDATE SONG
PUT http://localhost:3000/songs/123

### DELETE SONG
DELETE http://localhost:3000/songs/123
