### CREATE SONG
POST http://localhost:3000/api/songs
Content-Type: application/json

{
    "title": "Where are U now",
    "artists": ["Justin Bieber", "Diplo", "Skrillix"],
    "album": "Where are U now",
    "releasedDate": "1712492200",
    "duration": "02:54"
}

### FETCH ALL SONGS
GET http://localhost:3000/api/songs

### FETCH SINGLE SONG
GET http://localhost:3000/api/songs/04eec047-c16e-403c-ac75-4bf9670c5772

### UPDATE SONG
PUT http://localhost:3000/api/songs/123

### DELETE SONG
DELETE http://localhost:3000/api/songs/123
